
version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5601:5432"
    environment:
      POSTGRES_USER: offboardinguser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: offboardingdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - offboarding-net

  backend:
    build: ./Backend
    container_name: backend-service
    ports:
      - "3601:3601"
    environment:
      DB_USER: offboardinguser
      DB_PASSWORD: secretpassword
      DB_HOST: postgres
      DB_NAME: offboardingdb
      DB_PORT: 5432
      PORT: 3601
    depends_on:
      - postgres
    networks:
      - offboarding-net

  employee-offboarding:
    build: ./employee-offboarding
    container_name: employee-offboarding-ui
    ports:
      - "8602:80"
    depends_on:
      - backend
    networks:
      - offboarding-net

  hr-offboarding:
    build: ./hr-offboarding
    container_name: hr-offboarding-ui
    ports:
      - "8603:80"
    depends_on:
      - backend
    networks:
      - offboarding-net

volumes:
  pgdata:

networks:
  offboarding-net:
  
